// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoqT7Hn6-F-KunHEWytmdTw4SsWuMRMfo',
    appId: '1:511479371724:web:f970c80b1e9dc675f92f69',
    messagingSenderId: '511479371724',
    projectId: 'inkbr-4760f',
    authDomain: 'inkbr-4760f.firebaseapp.com',
    storageBucket: 'inkbr-4760f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB40M7AvYoIOVApJLtKE9YLdbsgbb1jHVU',
    appId: '1:511479371724:android:1eacaba561f7b794f92f69',
    messagingSenderId: '511479371724',
    projectId: 'inkbr-4760f',
    storageBucket: 'inkbr-4760f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ8Xgetoxb_mVJBwxi6NxLZWxvwnX2sl8',
    appId: '1:511479371724:ios:2f4762a93ced3c00f92f69',
    messagingSenderId: '511479371724',
    projectId: 'inkbr-4760f',
    storageBucket: 'inkbr-4760f.firebasestorage.app',
    iosBundleId: 'com.example.projetoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ8Xgetoxb_mVJBwxi6NxLZWxvwnX2sl8',
    appId: '1:511479371724:ios:2f4762a93ced3c00f92f69',
    messagingSenderId: '511479371724',
    projectId: 'inkbr-4760f',
    storageBucket: 'inkbr-4760f.firebasestorage.app',
    iosBundleId: 'com.example.projetoFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoqT7Hn6-F-KunHEWytmdTw4SsWuMRMfo',
    appId: '1:511479371724:web:ba6b3d455861465cf92f69',
    messagingSenderId: '511479371724',
    projectId: 'inkbr-4760f',
    authDomain: 'inkbr-4760f.firebaseapp.com',
    storageBucket: 'inkbr-4760f.firebasestorage.app',
  );
}
